// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetUserFeatureFlagsReader is a Reader for the GetUserFeatureFlags structure.
type GetUserFeatureFlagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserFeatureFlagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserFeatureFlagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserFeatureFlagsOK creates a GetUserFeatureFlagsOK with default headers values
func NewGetUserFeatureFlagsOK() *GetUserFeatureFlagsOK {
	return &GetUserFeatureFlagsOK{}
}

/* GetUserFeatureFlagsOK describes a response with status code 200, with default header values.

OK
*/
type GetUserFeatureFlagsOK struct {
	Payload []string
}

func (o *GetUserFeatureFlagsOK) Error() string {
	return fmt.Sprintf("[GET /v0/users/{id}/feature-flags][%d] getUserFeatureFlagsOK  %+v", 200, o.Payload)
}
func (o *GetUserFeatureFlagsOK) GetPayload() []string {
	return o.Payload
}

func (o *GetUserFeatureFlagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
