// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserFeatureFlagsParams creates a new GetUserFeatureFlagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserFeatureFlagsParams() *GetUserFeatureFlagsParams {
	return &GetUserFeatureFlagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserFeatureFlagsParamsWithTimeout creates a new GetUserFeatureFlagsParams object
// with the ability to set a timeout on a request.
func NewGetUserFeatureFlagsParamsWithTimeout(timeout time.Duration) *GetUserFeatureFlagsParams {
	return &GetUserFeatureFlagsParams{
		timeout: timeout,
	}
}

// NewGetUserFeatureFlagsParamsWithContext creates a new GetUserFeatureFlagsParams object
// with the ability to set a context for a request.
func NewGetUserFeatureFlagsParamsWithContext(ctx context.Context) *GetUserFeatureFlagsParams {
	return &GetUserFeatureFlagsParams{
		Context: ctx,
	}
}

// NewGetUserFeatureFlagsParamsWithHTTPClient creates a new GetUserFeatureFlagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserFeatureFlagsParamsWithHTTPClient(client *http.Client) *GetUserFeatureFlagsParams {
	return &GetUserFeatureFlagsParams{
		HTTPClient: client,
	}
}

/* GetUserFeatureFlagsParams contains all the parameters to send to the API endpoint
   for the get user feature flags operation.

   Typically these are written to a http.Request.
*/
type GetUserFeatureFlagsParams struct {

	/* ID.

	   User ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user feature flags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserFeatureFlagsParams) WithDefaults() *GetUserFeatureFlagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user feature flags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserFeatureFlagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user feature flags params
func (o *GetUserFeatureFlagsParams) WithTimeout(timeout time.Duration) *GetUserFeatureFlagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user feature flags params
func (o *GetUserFeatureFlagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user feature flags params
func (o *GetUserFeatureFlagsParams) WithContext(ctx context.Context) *GetUserFeatureFlagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user feature flags params
func (o *GetUserFeatureFlagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user feature flags params
func (o *GetUserFeatureFlagsParams) WithHTTPClient(client *http.Client) *GetUserFeatureFlagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user feature flags params
func (o *GetUserFeatureFlagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get user feature flags params
func (o *GetUserFeatureFlagsParams) WithID(id string) *GetUserFeatureFlagsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get user feature flags params
func (o *GetUserFeatureFlagsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserFeatureFlagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
