// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserSshkeyParams creates a new GetUserSshkeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserSshkeyParams() *GetUserSshkeyParams {
	return &GetUserSshkeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserSshkeyParamsWithTimeout creates a new GetUserSshkeyParams object
// with the ability to set a timeout on a request.
func NewGetUserSshkeyParamsWithTimeout(timeout time.Duration) *GetUserSshkeyParams {
	return &GetUserSshkeyParams{
		timeout: timeout,
	}
}

// NewGetUserSshkeyParamsWithContext creates a new GetUserSshkeyParams object
// with the ability to set a context for a request.
func NewGetUserSshkeyParamsWithContext(ctx context.Context) *GetUserSshkeyParams {
	return &GetUserSshkeyParams{
		Context: ctx,
	}
}

// NewGetUserSshkeyParamsWithHTTPClient creates a new GetUserSshkeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserSshkeyParamsWithHTTPClient(client *http.Client) *GetUserSshkeyParams {
	return &GetUserSshkeyParams{
		HTTPClient: client,
	}
}

/* GetUserSshkeyParams contains all the parameters to send to the API endpoint
   for the get user sshkey operation.

   Typically these are written to a http.Request.
*/
type GetUserSshkeyParams struct {

	/* ID.

	   User ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSshkeyParams) WithDefaults() *GetUserSshkeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSshkeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user sshkey params
func (o *GetUserSshkeyParams) WithTimeout(timeout time.Duration) *GetUserSshkeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user sshkey params
func (o *GetUserSshkeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user sshkey params
func (o *GetUserSshkeyParams) WithContext(ctx context.Context) *GetUserSshkeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user sshkey params
func (o *GetUserSshkeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user sshkey params
func (o *GetUserSshkeyParams) WithHTTPClient(client *http.Client) *GetUserSshkeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user sshkey params
func (o *GetUserSshkeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get user sshkey params
func (o *GetUserSshkeyParams) WithID(id string) *GetUserSshkeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get user sshkey params
func (o *GetUserSshkeyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserSshkeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
