// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cdr.dev/coder-cli/sdk2/models"
)

// ListUsersReader is a Reader for the ListUsers structure.
type ListUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListUsersOK creates a ListUsersOK with default headers values
func NewListUsersOK() *ListUsersOK {
	return &ListUsersOK{}
}

/* ListUsersOK describes a response with status code 200, with default header values.

OK
*/
type ListUsersOK struct {
	Payload *ListUsersOKBody
}

func (o *ListUsersOK) Error() string {
	return fmt.Sprintf("[GET /v0/users][%d] listUsersOK  %+v", 200, o.Payload)
}
func (o *ListUsersOK) GetPayload() *ListUsersOKBody {
	return o.Payload
}

func (o *ListUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListUsersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ListUsersOKBody list users o k body
swagger:model ListUsersOKBody
*/
type ListUsersOKBody struct {
	models.PagedResponse

	// data
	Data []*models.User `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ListUsersOKBody) UnmarshalJSON(raw []byte) error {
	// ListUsersOKBodyAO0
	var listUsersOKBodyAO0 models.PagedResponse
	if err := swag.ReadJSON(raw, &listUsersOKBodyAO0); err != nil {
		return err
	}
	o.PagedResponse = listUsersOKBodyAO0

	// ListUsersOKBodyAO1
	var dataListUsersOKBodyAO1 struct {
		Data []*models.User `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataListUsersOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataListUsersOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ListUsersOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	listUsersOKBodyAO0, err := swag.WriteJSON(o.PagedResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, listUsersOKBodyAO0)
	var dataListUsersOKBodyAO1 struct {
		Data []*models.User `json:"data"`
	}

	dataListUsersOKBodyAO1.Data = o.Data

	jsonDataListUsersOKBodyAO1, errListUsersOKBodyAO1 := swag.WriteJSON(dataListUsersOKBodyAO1)
	if errListUsersOKBodyAO1 != nil {
		return nil, errListUsersOKBodyAO1
	}
	_parts = append(_parts, jsonDataListUsersOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this list users o k body
func (o *ListUsersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.PagedResponse
	if err := o.PagedResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListUsersOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listUsersOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list users o k body based on the context it is used
func (o *ListUsersOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.PagedResponse
	if err := o.PagedResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListUsersOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("listUsersOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListUsersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListUsersOKBody) UnmarshalBinary(b []byte) error {
	var res ListUsersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
