// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRegenUserSshkeyParams creates a new RegenUserSshkeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegenUserSshkeyParams() *RegenUserSshkeyParams {
	return &RegenUserSshkeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegenUserSshkeyParamsWithTimeout creates a new RegenUserSshkeyParams object
// with the ability to set a timeout on a request.
func NewRegenUserSshkeyParamsWithTimeout(timeout time.Duration) *RegenUserSshkeyParams {
	return &RegenUserSshkeyParams{
		timeout: timeout,
	}
}

// NewRegenUserSshkeyParamsWithContext creates a new RegenUserSshkeyParams object
// with the ability to set a context for a request.
func NewRegenUserSshkeyParamsWithContext(ctx context.Context) *RegenUserSshkeyParams {
	return &RegenUserSshkeyParams{
		Context: ctx,
	}
}

// NewRegenUserSshkeyParamsWithHTTPClient creates a new RegenUserSshkeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegenUserSshkeyParamsWithHTTPClient(client *http.Client) *RegenUserSshkeyParams {
	return &RegenUserSshkeyParams{
		HTTPClient: client,
	}
}

/* RegenUserSshkeyParams contains all the parameters to send to the API endpoint
   for the regen user sshkey operation.

   Typically these are written to a http.Request.
*/
type RegenUserSshkeyParams struct {

	/* ID.

	   User ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the regen user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegenUserSshkeyParams) WithDefaults() *RegenUserSshkeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the regen user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegenUserSshkeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the regen user sshkey params
func (o *RegenUserSshkeyParams) WithTimeout(timeout time.Duration) *RegenUserSshkeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the regen user sshkey params
func (o *RegenUserSshkeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the regen user sshkey params
func (o *RegenUserSshkeyParams) WithContext(ctx context.Context) *RegenUserSshkeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the regen user sshkey params
func (o *RegenUserSshkeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the regen user sshkey params
func (o *RegenUserSshkeyParams) WithHTTPClient(client *http.Client) *RegenUserSshkeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the regen user sshkey params
func (o *RegenUserSshkeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the regen user sshkey params
func (o *RegenUserSshkeyParams) WithID(id string) *RegenUserSshkeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the regen user sshkey params
func (o *RegenUserSshkeyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RegenUserSshkeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
