// Code generated by go-swagger; DO NOT EDIT.

package resource_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResourcePoolParams creates a new GetResourcePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResourcePoolParams() *GetResourcePoolParams {
	return &GetResourcePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourcePoolParamsWithTimeout creates a new GetResourcePoolParams object
// with the ability to set a timeout on a request.
func NewGetResourcePoolParamsWithTimeout(timeout time.Duration) *GetResourcePoolParams {
	return &GetResourcePoolParams{
		timeout: timeout,
	}
}

// NewGetResourcePoolParamsWithContext creates a new GetResourcePoolParams object
// with the ability to set a context for a request.
func NewGetResourcePoolParamsWithContext(ctx context.Context) *GetResourcePoolParams {
	return &GetResourcePoolParams{
		Context: ctx,
	}
}

// NewGetResourcePoolParamsWithHTTPClient creates a new GetResourcePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResourcePoolParamsWithHTTPClient(client *http.Client) *GetResourcePoolParams {
	return &GetResourcePoolParams{
		HTTPClient: client,
	}
}

/* GetResourcePoolParams contains all the parameters to send to the API endpoint
   for the get resource pool operation.

   Typically these are written to a http.Request.
*/
type GetResourcePoolParams struct {

	/* ID.

	   Resource Pool ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resource pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourcePoolParams) WithDefaults() *GetResourcePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resource pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourcePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resource pool params
func (o *GetResourcePoolParams) WithTimeout(timeout time.Duration) *GetResourcePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource pool params
func (o *GetResourcePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource pool params
func (o *GetResourcePoolParams) WithContext(ctx context.Context) *GetResourcePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource pool params
func (o *GetResourcePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource pool params
func (o *GetResourcePoolParams) WithHTTPClient(client *http.Client) *GetResourcePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource pool params
func (o *GetResourcePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get resource pool params
func (o *GetResourcePoolParams) WithID(id string) *GetResourcePoolParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get resource pool params
func (o *GetResourcePoolParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourcePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
