// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// NewSetConfigEnvironmentsParams creates a new SetConfigEnvironmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetConfigEnvironmentsParams() *SetConfigEnvironmentsParams {
	return &SetConfigEnvironmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetConfigEnvironmentsParamsWithTimeout creates a new SetConfigEnvironmentsParams object
// with the ability to set a timeout on a request.
func NewSetConfigEnvironmentsParamsWithTimeout(timeout time.Duration) *SetConfigEnvironmentsParams {
	return &SetConfigEnvironmentsParams{
		timeout: timeout,
	}
}

// NewSetConfigEnvironmentsParamsWithContext creates a new SetConfigEnvironmentsParams object
// with the ability to set a context for a request.
func NewSetConfigEnvironmentsParamsWithContext(ctx context.Context) *SetConfigEnvironmentsParams {
	return &SetConfigEnvironmentsParams{
		Context: ctx,
	}
}

// NewSetConfigEnvironmentsParamsWithHTTPClient creates a new SetConfigEnvironmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetConfigEnvironmentsParamsWithHTTPClient(client *http.Client) *SetConfigEnvironmentsParams {
	return &SetConfigEnvironmentsParams{
		HTTPClient: client,
	}
}

/* SetConfigEnvironmentsParams contains all the parameters to send to the API endpoint
   for the set config environments operation.

   Typically these are written to a http.Request.
*/
type SetConfigEnvironmentsParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.ConfigEnvironments

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set config environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetConfigEnvironmentsParams) WithDefaults() *SetConfigEnvironmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set config environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetConfigEnvironmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set config environments params
func (o *SetConfigEnvironmentsParams) WithTimeout(timeout time.Duration) *SetConfigEnvironmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set config environments params
func (o *SetConfigEnvironmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set config environments params
func (o *SetConfigEnvironmentsParams) WithContext(ctx context.Context) *SetConfigEnvironmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set config environments params
func (o *SetConfigEnvironmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set config environments params
func (o *SetConfigEnvironmentsParams) WithHTTPClient(client *http.Client) *SetConfigEnvironmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set config environments params
func (o *SetConfigEnvironmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the set config environments params
func (o *SetConfigEnvironmentsParams) WithRequest(request *models.ConfigEnvironments) *SetConfigEnvironmentsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the set config environments params
func (o *SetConfigEnvironmentsParams) SetRequest(request *models.ConfigEnvironments) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *SetConfigEnvironmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
