// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetImageParams creates a new GetImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageParams() *GetImageParams {
	return &GetImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageParamsWithTimeout creates a new GetImageParams object
// with the ability to set a timeout on a request.
func NewGetImageParamsWithTimeout(timeout time.Duration) *GetImageParams {
	return &GetImageParams{
		timeout: timeout,
	}
}

// NewGetImageParamsWithContext creates a new GetImageParams object
// with the ability to set a context for a request.
func NewGetImageParamsWithContext(ctx context.Context) *GetImageParams {
	return &GetImageParams{
		Context: ctx,
	}
}

// NewGetImageParamsWithHTTPClient creates a new GetImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageParamsWithHTTPClient(client *http.Client) *GetImageParams {
	return &GetImageParams{
		HTTPClient: client,
	}
}

/* GetImageParams contains all the parameters to send to the API endpoint
   for the get image operation.

   Typically these are written to a http.Request.
*/
type GetImageParams struct {

	/* Envs.

	   Populate 'environments' with environments using this image
	*/
	Envs *bool

	/* ID.

	   Image ID
	*/
	ID string

	/* UserIds.

	   Populate 'user_ids' with User IDs using this image
	*/
	UserIds *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageParams) WithDefaults() *GetImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image params
func (o *GetImageParams) WithTimeout(timeout time.Duration) *GetImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image params
func (o *GetImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image params
func (o *GetImageParams) WithContext(ctx context.Context) *GetImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image params
func (o *GetImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) WithHTTPClient(client *http.Client) *GetImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvs adds the envs to the get image params
func (o *GetImageParams) WithEnvs(envs *bool) *GetImageParams {
	o.SetEnvs(envs)
	return o
}

// SetEnvs adds the envs to the get image params
func (o *GetImageParams) SetEnvs(envs *bool) {
	o.Envs = envs
}

// WithID adds the id to the get image params
func (o *GetImageParams) WithID(id string) *GetImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get image params
func (o *GetImageParams) SetID(id string) {
	o.ID = id
}

// WithUserIds adds the userIds to the get image params
func (o *GetImageParams) WithUserIds(userIds *bool) *GetImageParams {
	o.SetUserIds(userIds)
	return o
}

// SetUserIds adds the userIds to the get image params
func (o *GetImageParams) SetUserIds(userIds *bool) {
	o.UserIds = userIds
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Envs != nil {

		// query param envs
		var qrEnvs bool

		if o.Envs != nil {
			qrEnvs = *o.Envs
		}
		qEnvs := swag.FormatBool(qrEnvs)
		if qEnvs != "" {

			if err := r.SetQueryParam("envs", qEnvs); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.UserIds != nil {

		// query param user_ids
		var qrUserIds bool

		if o.UserIds != nil {
			qrUserIds = *o.UserIds
		}
		qUserIds := swag.FormatBool(qrUserIds)
		if qUserIds != "" {

			if err := r.SetQueryParam("user_ids", qUserIds); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
