// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetImageRegistryTagsReader is a Reader for the GetImageRegistryTags structure.
type GetImageRegistryTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageRegistryTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImageRegistryTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetImageRegistryTagsOK creates a GetImageRegistryTagsOK with default headers values
func NewGetImageRegistryTagsOK() *GetImageRegistryTagsOK {
	return &GetImageRegistryTagsOK{}
}

/* GetImageRegistryTagsOK describes a response with status code 200, with default header values.

OK
*/
type GetImageRegistryTagsOK struct {
	Payload []string
}

func (o *GetImageRegistryTagsOK) Error() string {
	return fmt.Sprintf("[GET /v0/images/{id}/registry-tags][%d] getImageRegistryTagsOK  %+v", 200, o.Payload)
}
func (o *GetImageRegistryTagsOK) GetPayload() []string {
	return o.Payload
}

func (o *GetImageRegistryTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
