// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetImageTagsReader is a Reader for the GetImageTags structure.
type GetImageTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImageTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetImageTagsOK creates a GetImageTagsOK with default headers values
func NewGetImageTagsOK() *GetImageTagsOK {
	return &GetImageTagsOK{}
}

/* GetImageTagsOK describes a response with status code 200, with default header values.

OK
*/
type GetImageTagsOK struct {
	Payload []*models.ImageTag
}

func (o *GetImageTagsOK) Error() string {
	return fmt.Sprintf("[GET /v0/images/{id}/tags][%d] getImageTagsOK  %+v", 200, o.Payload)
}
func (o *GetImageTagsOK) GetPayload() []*models.ImageTag {
	return o.Payload
}

func (o *GetImageTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
