// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetImageTagsParams creates a new GetImageTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageTagsParams() *GetImageTagsParams {
	return &GetImageTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageTagsParamsWithTimeout creates a new GetImageTagsParams object
// with the ability to set a timeout on a request.
func NewGetImageTagsParamsWithTimeout(timeout time.Duration) *GetImageTagsParams {
	return &GetImageTagsParams{
		timeout: timeout,
	}
}

// NewGetImageTagsParamsWithContext creates a new GetImageTagsParams object
// with the ability to set a context for a request.
func NewGetImageTagsParamsWithContext(ctx context.Context) *GetImageTagsParams {
	return &GetImageTagsParams{
		Context: ctx,
	}
}

// NewGetImageTagsParamsWithHTTPClient creates a new GetImageTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageTagsParamsWithHTTPClient(client *http.Client) *GetImageTagsParams {
	return &GetImageTagsParams{
		HTTPClient: client,
	}
}

/* GetImageTagsParams contains all the parameters to send to the API endpoint
   for the get image tags operation.

   Typically these are written to a http.Request.
*/
type GetImageTagsParams struct {

	/* ID.

	   Image ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageTagsParams) WithDefaults() *GetImageTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image tags params
func (o *GetImageTagsParams) WithTimeout(timeout time.Duration) *GetImageTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image tags params
func (o *GetImageTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image tags params
func (o *GetImageTagsParams) WithContext(ctx context.Context) *GetImageTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image tags params
func (o *GetImageTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image tags params
func (o *GetImageTagsParams) WithHTTPClient(client *http.Client) *GetImageTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image tags params
func (o *GetImageTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get image tags params
func (o *GetImageTagsParams) WithID(id string) *GetImageTagsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get image tags params
func (o *GetImageTagsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
