// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetImageEnvironmentsParams creates a new GetImageEnvironmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageEnvironmentsParams() *GetImageEnvironmentsParams {
	return &GetImageEnvironmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageEnvironmentsParamsWithTimeout creates a new GetImageEnvironmentsParams object
// with the ability to set a timeout on a request.
func NewGetImageEnvironmentsParamsWithTimeout(timeout time.Duration) *GetImageEnvironmentsParams {
	return &GetImageEnvironmentsParams{
		timeout: timeout,
	}
}

// NewGetImageEnvironmentsParamsWithContext creates a new GetImageEnvironmentsParams object
// with the ability to set a context for a request.
func NewGetImageEnvironmentsParamsWithContext(ctx context.Context) *GetImageEnvironmentsParams {
	return &GetImageEnvironmentsParams{
		Context: ctx,
	}
}

// NewGetImageEnvironmentsParamsWithHTTPClient creates a new GetImageEnvironmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageEnvironmentsParamsWithHTTPClient(client *http.Client) *GetImageEnvironmentsParams {
	return &GetImageEnvironmentsParams{
		HTTPClient: client,
	}
}

/* GetImageEnvironmentsParams contains all the parameters to send to the API endpoint
   for the get image environments operation.

   Typically these are written to a http.Request.
*/
type GetImageEnvironmentsParams struct {

	/* After.

	   Get environments after id. Cannot set both 'after' and 'before'
	*/
	After *string

	/* Before.

	   Get environments before id. Cannot set both 'before' and 'after'
	*/
	Before *string

	/* ID.

	   Image ID
	*/
	ID string

	/* Limit.

	   Max number of environments to return
	*/
	Limit *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageEnvironmentsParams) WithDefaults() *GetImageEnvironmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageEnvironmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image environments params
func (o *GetImageEnvironmentsParams) WithTimeout(timeout time.Duration) *GetImageEnvironmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image environments params
func (o *GetImageEnvironmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image environments params
func (o *GetImageEnvironmentsParams) WithContext(ctx context.Context) *GetImageEnvironmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image environments params
func (o *GetImageEnvironmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image environments params
func (o *GetImageEnvironmentsParams) WithHTTPClient(client *http.Client) *GetImageEnvironmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image environments params
func (o *GetImageEnvironmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAfter adds the after to the get image environments params
func (o *GetImageEnvironmentsParams) WithAfter(after *string) *GetImageEnvironmentsParams {
	o.SetAfter(after)
	return o
}

// SetAfter adds the after to the get image environments params
func (o *GetImageEnvironmentsParams) SetAfter(after *string) {
	o.After = after
}

// WithBefore adds the before to the get image environments params
func (o *GetImageEnvironmentsParams) WithBefore(before *string) *GetImageEnvironmentsParams {
	o.SetBefore(before)
	return o
}

// SetBefore adds the before to the get image environments params
func (o *GetImageEnvironmentsParams) SetBefore(before *string) {
	o.Before = before
}

// WithID adds the id to the get image environments params
func (o *GetImageEnvironmentsParams) WithID(id string) *GetImageEnvironmentsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get image environments params
func (o *GetImageEnvironmentsParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the get image environments params
func (o *GetImageEnvironmentsParams) WithLimit(limit *int64) *GetImageEnvironmentsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get image environments params
func (o *GetImageEnvironmentsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageEnvironmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.After != nil {

		// query param after
		var qrAfter string

		if o.After != nil {
			qrAfter = *o.After
		}
		qAfter := qrAfter
		if qAfter != "" {

			if err := r.SetQueryParam("after", qAfter); err != nil {
				return err
			}
		}
	}

	if o.Before != nil {

		// query param before
		var qrBefore string

		if o.Before != nil {
			qrBefore = *o.Before
		}
		qBefore := qrBefore
		if qBefore != "" {

			if err := r.SetQueryParam("before", qBefore); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
