// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// NewImportOrgImageParams creates a new ImportOrgImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImportOrgImageParams() *ImportOrgImageParams {
	return &ImportOrgImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImportOrgImageParamsWithTimeout creates a new ImportOrgImageParams object
// with the ability to set a timeout on a request.
func NewImportOrgImageParamsWithTimeout(timeout time.Duration) *ImportOrgImageParams {
	return &ImportOrgImageParams{
		timeout: timeout,
	}
}

// NewImportOrgImageParamsWithContext creates a new ImportOrgImageParams object
// with the ability to set a context for a request.
func NewImportOrgImageParamsWithContext(ctx context.Context) *ImportOrgImageParams {
	return &ImportOrgImageParams{
		Context: ctx,
	}
}

// NewImportOrgImageParamsWithHTTPClient creates a new ImportOrgImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewImportOrgImageParamsWithHTTPClient(client *http.Client) *ImportOrgImageParams {
	return &ImportOrgImageParams{
		HTTPClient: client,
	}
}

/* ImportOrgImageParams contains all the parameters to send to the API endpoint
   for the import org image operation.

   Typically these are written to a http.Request.
*/
type ImportOrgImageParams struct {

	/* ID.

	   Org ID
	*/
	ID string

	/* Request.

	   Request body
	*/
	Request *models.ImportImageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the import org image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportOrgImageParams) WithDefaults() *ImportOrgImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the import org image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportOrgImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the import org image params
func (o *ImportOrgImageParams) WithTimeout(timeout time.Duration) *ImportOrgImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import org image params
func (o *ImportOrgImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import org image params
func (o *ImportOrgImageParams) WithContext(ctx context.Context) *ImportOrgImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import org image params
func (o *ImportOrgImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import org image params
func (o *ImportOrgImageParams) WithHTTPClient(client *http.Client) *ImportOrgImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import org image params
func (o *ImportOrgImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the import org image params
func (o *ImportOrgImageParams) WithID(id string) *ImportOrgImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the import org image params
func (o *ImportOrgImageParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the import org image params
func (o *ImportOrgImageParams) WithRequest(request *models.ImportImageRequest) *ImportOrgImageParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the import org image params
func (o *ImportOrgImageParams) SetRequest(request *models.ImportImageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *ImportOrgImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
