// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// ImportOrgImageReader is a Reader for the ImportOrgImage structure.
type ImportOrgImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportOrgImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewImportOrgImageCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImportOrgImageCreated creates a ImportOrgImageCreated with default headers values
func NewImportOrgImageCreated() *ImportOrgImageCreated {
	return &ImportOrgImageCreated{}
}

/* ImportOrgImageCreated describes a response with status code 201, with default header values.

Created
*/
type ImportOrgImageCreated struct {
	Payload *models.Image
}

func (o *ImportOrgImageCreated) Error() string {
	return fmt.Sprintf("[POST /v0/images][%d] importOrgImageCreated  %+v", 201, o.Payload)
}
func (o *ImportOrgImageCreated) GetPayload() *models.Image {
	return o.Payload
}

func (o *ImportOrgImageCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Image)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
