// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// ImportImageTagReader is a Reader for the ImportImageTag structure.
type ImportImageTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportImageTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewImportImageTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImportImageTagOK creates a ImportImageTagOK with default headers values
func NewImportImageTagOK() *ImportImageTagOK {
	return &ImportImageTagOK{}
}

/* ImportImageTagOK describes a response with status code 200, with default header values.

OK
*/
type ImportImageTagOK struct {
	Payload *models.ImageTag
}

func (o *ImportImageTagOK) Error() string {
	return fmt.Sprintf("[POST /v0/images/{id}/tags][%d] importImageTagOK  %+v", 200, o.Payload)
}
func (o *ImportImageTagOK) GetPayload() *models.ImageTag {
	return o.Payload
}

func (o *ImportImageTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
