// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// NewImportImageTagParams creates a new ImportImageTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImportImageTagParams() *ImportImageTagParams {
	return &ImportImageTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImportImageTagParamsWithTimeout creates a new ImportImageTagParams object
// with the ability to set a timeout on a request.
func NewImportImageTagParamsWithTimeout(timeout time.Duration) *ImportImageTagParams {
	return &ImportImageTagParams{
		timeout: timeout,
	}
}

// NewImportImageTagParamsWithContext creates a new ImportImageTagParams object
// with the ability to set a context for a request.
func NewImportImageTagParamsWithContext(ctx context.Context) *ImportImageTagParams {
	return &ImportImageTagParams{
		Context: ctx,
	}
}

// NewImportImageTagParamsWithHTTPClient creates a new ImportImageTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewImportImageTagParamsWithHTTPClient(client *http.Client) *ImportImageTagParams {
	return &ImportImageTagParams{
		HTTPClient: client,
	}
}

/* ImportImageTagParams contains all the parameters to send to the API endpoint
   for the import image tag operation.

   Typically these are written to a http.Request.
*/
type ImportImageTagParams struct {

	/* Body.

	   Request Body
	*/
	Body *models.ImportImageTagRequest

	/* ID.

	   Image ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the import image tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportImageTagParams) WithDefaults() *ImportImageTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the import image tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportImageTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the import image tag params
func (o *ImportImageTagParams) WithTimeout(timeout time.Duration) *ImportImageTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import image tag params
func (o *ImportImageTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import image tag params
func (o *ImportImageTagParams) WithContext(ctx context.Context) *ImportImageTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import image tag params
func (o *ImportImageTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import image tag params
func (o *ImportImageTagParams) WithHTTPClient(client *http.Client) *ImportImageTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import image tag params
func (o *ImportImageTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the import image tag params
func (o *ImportImageTagParams) WithBody(body *models.ImportImageTagRequest) *ImportImageTagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the import image tag params
func (o *ImportImageTagParams) SetBody(body *models.ImportImageTagRequest) {
	o.Body = body
}

// WithID adds the id to the import image tag params
func (o *ImportImageTagParams) WithID(id string) *ImportImageTagParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the import image tag params
func (o *ImportImageTagParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ImportImageTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
