// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// ActiveUsersReader is a Reader for the ActiveUsers structure.
type ActiveUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActiveUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActiveUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActiveUsersOK creates a ActiveUsersOK with default headers values
func NewActiveUsersOK() *ActiveUsersOK {
	return &ActiveUsersOK{}
}

/* ActiveUsersOK describes a response with status code 200, with default header values.

OK
*/
type ActiveUsersOK struct {
	Payload *models.UserActivityResponse
}

func (o *ActiveUsersOK) Error() string {
	return fmt.Sprintf("[GET /v0/metrics/site/active-users][%d] activeUsersOK  %+v", 200, o.Payload)
}
func (o *ActiveUsersOK) GetPayload() *models.UserActivityResponse {
	return o.Payload
}

func (o *ActiveUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
