// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GenerateApplicationAPIKeyReader is a Reader for the GenerateApplicationAPIKey structure.
type GenerateApplicationAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateApplicationAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGenerateApplicationAPIKeyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGenerateApplicationAPIKeyCreated creates a GenerateApplicationAPIKeyCreated with default headers values
func NewGenerateApplicationAPIKeyCreated() *GenerateApplicationAPIKeyCreated {
	return &GenerateApplicationAPIKeyCreated{}
}

/* GenerateApplicationAPIKeyCreated describes a response with status code 201, with default header values.

Created
*/
type GenerateApplicationAPIKeyCreated struct {
	Payload *models.GenerateApplicationAPIKeyResponse
}

func (o *GenerateApplicationAPIKeyCreated) Error() string {
	return fmt.Sprintf("[POST /v0/api-keys/{user_id}][%d] generateApplicationApiKeyCreated  %+v", 201, o.Payload)
}
func (o *GenerateApplicationAPIKeyCreated) GetPayload() *models.GenerateApplicationAPIKeyResponse {
	return o.Payload
}

func (o *GenerateApplicationAPIKeyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenerateApplicationAPIKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
