// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateApplicationAPIKeyParams creates a new GenerateApplicationAPIKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateApplicationAPIKeyParams() *GenerateApplicationAPIKeyParams {
	return &GenerateApplicationAPIKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateApplicationAPIKeyParamsWithTimeout creates a new GenerateApplicationAPIKeyParams object
// with the ability to set a timeout on a request.
func NewGenerateApplicationAPIKeyParamsWithTimeout(timeout time.Duration) *GenerateApplicationAPIKeyParams {
	return &GenerateApplicationAPIKeyParams{
		timeout: timeout,
	}
}

// NewGenerateApplicationAPIKeyParamsWithContext creates a new GenerateApplicationAPIKeyParams object
// with the ability to set a context for a request.
func NewGenerateApplicationAPIKeyParamsWithContext(ctx context.Context) *GenerateApplicationAPIKeyParams {
	return &GenerateApplicationAPIKeyParams{
		Context: ctx,
	}
}

// NewGenerateApplicationAPIKeyParamsWithHTTPClient creates a new GenerateApplicationAPIKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateApplicationAPIKeyParamsWithHTTPClient(client *http.Client) *GenerateApplicationAPIKeyParams {
	return &GenerateApplicationAPIKeyParams{
		HTTPClient: client,
	}
}

/* GenerateApplicationAPIKeyParams contains all the parameters to send to the API endpoint
   for the generate application api key operation.

   Typically these are written to a http.Request.
*/
type GenerateApplicationAPIKeyParams struct {

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate application api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateApplicationAPIKeyParams) WithDefaults() *GenerateApplicationAPIKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate application api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateApplicationAPIKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) WithTimeout(timeout time.Duration) *GenerateApplicationAPIKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) WithContext(ctx context.Context) *GenerateApplicationAPIKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) WithHTTPClient(client *http.Client) *GenerateApplicationAPIKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) WithUserID(userID string) *GenerateApplicationAPIKeyParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the generate application api key params
func (o *GenerateApplicationAPIKeyParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateApplicationAPIKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
