// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// ListAPIKeysReader is a Reader for the ListAPIKeys structure.
type ListAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListAPIKeysOK creates a ListAPIKeysOK with default headers values
func NewListAPIKeysOK() *ListAPIKeysOK {
	return &ListAPIKeysOK{}
}

/* ListAPIKeysOK describes a response with status code 200, with default header values.

OK
*/
type ListAPIKeysOK struct {
	Payload []*models.APIKey
}

func (o *ListAPIKeysOK) Error() string {
	return fmt.Sprintf("[GET /v0/api-keys/{user_id}][%d] listApiKeysOK  %+v", 200, o.Payload)
}
func (o *ListAPIKeysOK) GetPayload() []*models.APIKey {
	return o.Payload
}

func (o *ListAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
