// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRegenAPIKeyParams creates a new RegenAPIKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegenAPIKeyParams() *RegenAPIKeyParams {
	return &RegenAPIKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegenAPIKeyParamsWithTimeout creates a new RegenAPIKeyParams object
// with the ability to set a timeout on a request.
func NewRegenAPIKeyParamsWithTimeout(timeout time.Duration) *RegenAPIKeyParams {
	return &RegenAPIKeyParams{
		timeout: timeout,
	}
}

// NewRegenAPIKeyParamsWithContext creates a new RegenAPIKeyParams object
// with the ability to set a context for a request.
func NewRegenAPIKeyParamsWithContext(ctx context.Context) *RegenAPIKeyParams {
	return &RegenAPIKeyParams{
		Context: ctx,
	}
}

// NewRegenAPIKeyParamsWithHTTPClient creates a new RegenAPIKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegenAPIKeyParamsWithHTTPClient(client *http.Client) *RegenAPIKeyParams {
	return &RegenAPIKeyParams{
		HTTPClient: client,
	}
}

/* RegenAPIKeyParams contains all the parameters to send to the API endpoint
   for the regen api key operation.

   Typically these are written to a http.Request.
*/
type RegenAPIKeyParams struct {

	/* ID.

	   API Key ID
	*/
	ID string

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the regen api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegenAPIKeyParams) WithDefaults() *RegenAPIKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the regen api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegenAPIKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the regen api key params
func (o *RegenAPIKeyParams) WithTimeout(timeout time.Duration) *RegenAPIKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the regen api key params
func (o *RegenAPIKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the regen api key params
func (o *RegenAPIKeyParams) WithContext(ctx context.Context) *RegenAPIKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the regen api key params
func (o *RegenAPIKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the regen api key params
func (o *RegenAPIKeyParams) WithHTTPClient(client *http.Client) *RegenAPIKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the regen api key params
func (o *RegenAPIKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the regen api key params
func (o *RegenAPIKeyParams) WithID(id string) *RegenAPIKeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the regen api key params
func (o *RegenAPIKeyParams) SetID(id string) {
	o.ID = id
}

// WithUserID adds the userID to the regen api key params
func (o *RegenAPIKeyParams) WithUserID(userID string) *RegenAPIKeyParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the regen api key params
func (o *RegenAPIKeyParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *RegenAPIKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
