// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentDevurlParams creates a new DeleteEnvironmentDevurlParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEnvironmentDevurlParams() *DeleteEnvironmentDevurlParams {
	return &DeleteEnvironmentDevurlParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnvironmentDevurlParamsWithTimeout creates a new DeleteEnvironmentDevurlParams object
// with the ability to set a timeout on a request.
func NewDeleteEnvironmentDevurlParamsWithTimeout(timeout time.Duration) *DeleteEnvironmentDevurlParams {
	return &DeleteEnvironmentDevurlParams{
		timeout: timeout,
	}
}

// NewDeleteEnvironmentDevurlParamsWithContext creates a new DeleteEnvironmentDevurlParams object
// with the ability to set a context for a request.
func NewDeleteEnvironmentDevurlParamsWithContext(ctx context.Context) *DeleteEnvironmentDevurlParams {
	return &DeleteEnvironmentDevurlParams{
		Context: ctx,
	}
}

// NewDeleteEnvironmentDevurlParamsWithHTTPClient creates a new DeleteEnvironmentDevurlParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEnvironmentDevurlParamsWithHTTPClient(client *http.Client) *DeleteEnvironmentDevurlParams {
	return &DeleteEnvironmentDevurlParams{
		HTTPClient: client,
	}
}

/* DeleteEnvironmentDevurlParams contains all the parameters to send to the API endpoint
   for the delete environment devurl operation.

   Typically these are written to a http.Request.
*/
type DeleteEnvironmentDevurlParams struct {

	/* Devurl.

	   DevURL ID
	*/
	Devurl string

	/* ID.

	   Environment ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete environment devurl params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnvironmentDevurlParams) WithDefaults() *DeleteEnvironmentDevurlParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete environment devurl params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnvironmentDevurlParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) WithTimeout(timeout time.Duration) *DeleteEnvironmentDevurlParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) WithContext(ctx context.Context) *DeleteEnvironmentDevurlParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) WithHTTPClient(client *http.Client) *DeleteEnvironmentDevurlParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevurl adds the devurl to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) WithDevurl(devurl string) *DeleteEnvironmentDevurlParams {
	o.SetDevurl(devurl)
	return o
}

// SetDevurl adds the devurl to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) SetDevurl(devurl string) {
	o.Devurl = devurl
}

// WithID adds the id to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) WithID(id string) *DeleteEnvironmentDevurlParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete environment devurl params
func (o *DeleteEnvironmentDevurlParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnvironmentDevurlParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devurl
	if err := r.SetPathParam("devurl", o.Devurl); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
