// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// DeleteEnvironmentDevurlReader is a Reader for the DeleteEnvironmentDevurl structure.
type DeleteEnvironmentDevurlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEnvironmentDevurlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteEnvironmentDevurlOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteEnvironmentDevurlOK creates a DeleteEnvironmentDevurlOK with default headers values
func NewDeleteEnvironmentDevurlOK() *DeleteEnvironmentDevurlOK {
	return &DeleteEnvironmentDevurlOK{}
}

/* DeleteEnvironmentDevurlOK describes a response with status code 200, with default header values.

OK
*/
type DeleteEnvironmentDevurlOK struct {
	Payload *models.SuccessMsg
}

func (o *DeleteEnvironmentDevurlOK) Error() string {
	return fmt.Sprintf("[DELETE /v0/environments/{id}/devurls/{devurl}][%d] deleteEnvironmentDevurlOK  %+v", 200, o.Payload)
}
func (o *DeleteEnvironmentDevurlOK) GetPayload() *models.SuccessMsg {
	return o.Payload
}

func (o *DeleteEnvironmentDevurlOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMsg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
