// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetEnvironmentDevurlsReader is a Reader for the GetEnvironmentDevurls structure.
type GetEnvironmentDevurlsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnvironmentDevurlsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnvironmentDevurlsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEnvironmentDevurlsOK creates a GetEnvironmentDevurlsOK with default headers values
func NewGetEnvironmentDevurlsOK() *GetEnvironmentDevurlsOK {
	return &GetEnvironmentDevurlsOK{}
}

/* GetEnvironmentDevurlsOK describes a response with status code 200, with default header values.

OK
*/
type GetEnvironmentDevurlsOK struct {
	Payload []*models.DevURL
}

func (o *GetEnvironmentDevurlsOK) Error() string {
	return fmt.Sprintf("[GET /v0/environments/{id}/devurls][%d] getEnvironmentDevurlsOK  %+v", 200, o.Payload)
}
func (o *GetEnvironmentDevurlsOK) GetPayload() []*models.DevURL {
	return o.Payload
}

func (o *GetEnvironmentDevurlsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
