// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEnvironmentDevurlStatusParams creates a new GetEnvironmentDevurlStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEnvironmentDevurlStatusParams() *GetEnvironmentDevurlStatusParams {
	return &GetEnvironmentDevurlStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnvironmentDevurlStatusParamsWithTimeout creates a new GetEnvironmentDevurlStatusParams object
// with the ability to set a timeout on a request.
func NewGetEnvironmentDevurlStatusParamsWithTimeout(timeout time.Duration) *GetEnvironmentDevurlStatusParams {
	return &GetEnvironmentDevurlStatusParams{
		timeout: timeout,
	}
}

// NewGetEnvironmentDevurlStatusParamsWithContext creates a new GetEnvironmentDevurlStatusParams object
// with the ability to set a context for a request.
func NewGetEnvironmentDevurlStatusParamsWithContext(ctx context.Context) *GetEnvironmentDevurlStatusParams {
	return &GetEnvironmentDevurlStatusParams{
		Context: ctx,
	}
}

// NewGetEnvironmentDevurlStatusParamsWithHTTPClient creates a new GetEnvironmentDevurlStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEnvironmentDevurlStatusParamsWithHTTPClient(client *http.Client) *GetEnvironmentDevurlStatusParams {
	return &GetEnvironmentDevurlStatusParams{
		HTTPClient: client,
	}
}

/* GetEnvironmentDevurlStatusParams contains all the parameters to send to the API endpoint
   for the get environment devurl status operation.

   Typically these are written to a http.Request.
*/
type GetEnvironmentDevurlStatusParams struct {

	/* Devurl.

	   DevURL ID
	*/
	Devurl string

	/* ID.

	   Environment ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get environment devurl status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvironmentDevurlStatusParams) WithDefaults() *GetEnvironmentDevurlStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get environment devurl status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnvironmentDevurlStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) WithTimeout(timeout time.Duration) *GetEnvironmentDevurlStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) WithContext(ctx context.Context) *GetEnvironmentDevurlStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) WithHTTPClient(client *http.Client) *GetEnvironmentDevurlStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevurl adds the devurl to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) WithDevurl(devurl string) *GetEnvironmentDevurlStatusParams {
	o.SetDevurl(devurl)
	return o
}

// SetDevurl adds the devurl to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) SetDevurl(devurl string) {
	o.Devurl = devurl
}

// WithID adds the id to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) WithID(id string) *GetEnvironmentDevurlStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get environment devurl status params
func (o *GetEnvironmentDevurlStatusParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnvironmentDevurlStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devurl
	if err := r.SetPathParam("devurl", o.Devurl); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
