// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEnvironmentDevurlStatusParams creates a new ListEnvironmentDevurlStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEnvironmentDevurlStatusParams() *ListEnvironmentDevurlStatusParams {
	return &ListEnvironmentDevurlStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEnvironmentDevurlStatusParamsWithTimeout creates a new ListEnvironmentDevurlStatusParams object
// with the ability to set a timeout on a request.
func NewListEnvironmentDevurlStatusParamsWithTimeout(timeout time.Duration) *ListEnvironmentDevurlStatusParams {
	return &ListEnvironmentDevurlStatusParams{
		timeout: timeout,
	}
}

// NewListEnvironmentDevurlStatusParamsWithContext creates a new ListEnvironmentDevurlStatusParams object
// with the ability to set a context for a request.
func NewListEnvironmentDevurlStatusParamsWithContext(ctx context.Context) *ListEnvironmentDevurlStatusParams {
	return &ListEnvironmentDevurlStatusParams{
		Context: ctx,
	}
}

// NewListEnvironmentDevurlStatusParamsWithHTTPClient creates a new ListEnvironmentDevurlStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEnvironmentDevurlStatusParamsWithHTTPClient(client *http.Client) *ListEnvironmentDevurlStatusParams {
	return &ListEnvironmentDevurlStatusParams{
		HTTPClient: client,
	}
}

/* ListEnvironmentDevurlStatusParams contains all the parameters to send to the API endpoint
   for the list environment devurl status operation.

   Typically these are written to a http.Request.
*/
type ListEnvironmentDevurlStatusParams struct {

	/* ID.

	   Environment ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list environment devurl status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnvironmentDevurlStatusParams) WithDefaults() *ListEnvironmentDevurlStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list environment devurl status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnvironmentDevurlStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) WithTimeout(timeout time.Duration) *ListEnvironmentDevurlStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) WithContext(ctx context.Context) *ListEnvironmentDevurlStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) WithHTTPClient(client *http.Client) *ListEnvironmentDevurlStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) WithID(id string) *ListEnvironmentDevurlStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list environment devurl status params
func (o *ListEnvironmentDevurlStatusParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListEnvironmentDevurlStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
