// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// UpdateEnvironmentDevurlReader is a Reader for the UpdateEnvironmentDevurl structure.
type UpdateEnvironmentDevurlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEnvironmentDevurlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateEnvironmentDevurlOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateEnvironmentDevurlOK creates a UpdateEnvironmentDevurlOK with default headers values
func NewUpdateEnvironmentDevurlOK() *UpdateEnvironmentDevurlOK {
	return &UpdateEnvironmentDevurlOK{}
}

/* UpdateEnvironmentDevurlOK describes a response with status code 200, with default header values.

OK
*/
type UpdateEnvironmentDevurlOK struct {
	Payload *models.DevURL
}

func (o *UpdateEnvironmentDevurlOK) Error() string {
	return fmt.Sprintf("[PUT /v0/environments/{id}/devurls/{devurl}][%d] updateEnvironmentDevurlOK  %+v", 200, o.Payload)
}
func (o *UpdateEnvironmentDevurlOK) GetPayload() *models.DevURL {
	return o.Payload
}

func (o *UpdateEnvironmentDevurlOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DevURL)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
