// Code generated by go-swagger; DO NOT EDIT.

package dev_u_r_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// NewUpdateEnvironmentDevurlParams creates a new UpdateEnvironmentDevurlParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEnvironmentDevurlParams() *UpdateEnvironmentDevurlParams {
	return &UpdateEnvironmentDevurlParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEnvironmentDevurlParamsWithTimeout creates a new UpdateEnvironmentDevurlParams object
// with the ability to set a timeout on a request.
func NewUpdateEnvironmentDevurlParamsWithTimeout(timeout time.Duration) *UpdateEnvironmentDevurlParams {
	return &UpdateEnvironmentDevurlParams{
		timeout: timeout,
	}
}

// NewUpdateEnvironmentDevurlParamsWithContext creates a new UpdateEnvironmentDevurlParams object
// with the ability to set a context for a request.
func NewUpdateEnvironmentDevurlParamsWithContext(ctx context.Context) *UpdateEnvironmentDevurlParams {
	return &UpdateEnvironmentDevurlParams{
		Context: ctx,
	}
}

// NewUpdateEnvironmentDevurlParamsWithHTTPClient creates a new UpdateEnvironmentDevurlParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEnvironmentDevurlParamsWithHTTPClient(client *http.Client) *UpdateEnvironmentDevurlParams {
	return &UpdateEnvironmentDevurlParams{
		HTTPClient: client,
	}
}

/* UpdateEnvironmentDevurlParams contains all the parameters to send to the API endpoint
   for the update environment devurl operation.

   Typically these are written to a http.Request.
*/
type UpdateEnvironmentDevurlParams struct {

	/* Devurl.

	   DevURL ID
	*/
	Devurl string

	/* ID.

	   Environment ID
	*/
	ID string

	/* Request.

	   Request Body
	*/
	Request *models.UpdateDevURLRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update environment devurl params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEnvironmentDevurlParams) WithDefaults() *UpdateEnvironmentDevurlParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update environment devurl params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEnvironmentDevurlParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithTimeout(timeout time.Duration) *UpdateEnvironmentDevurlParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithContext(ctx context.Context) *UpdateEnvironmentDevurlParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithHTTPClient(client *http.Client) *UpdateEnvironmentDevurlParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevurl adds the devurl to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithDevurl(devurl string) *UpdateEnvironmentDevurlParams {
	o.SetDevurl(devurl)
	return o
}

// SetDevurl adds the devurl to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetDevurl(devurl string) {
	o.Devurl = devurl
}

// WithID adds the id to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithID(id string) *UpdateEnvironmentDevurlParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) WithRequest(request *models.UpdateDevURLRequest) *UpdateEnvironmentDevurlParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update environment devurl params
func (o *UpdateEnvironmentDevurlParams) SetRequest(request *models.UpdateDevURLRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEnvironmentDevurlParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param devurl
	if err := r.SetPathParam("devurl", o.Devurl); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
