// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/client/api_keys"
	"cdr.dev/coder-cli/sdk2/client/audit_log"
	"cdr.dev/coder-cli/sdk2/client/config"
	"cdr.dev/coder-cli/sdk2/client/dev_u_r_ls"
	"cdr.dev/coder-cli/sdk2/client/environments"
	"cdr.dev/coder-cli/sdk2/client/images"
	"cdr.dev/coder-cli/sdk2/client/metrics"
	"cdr.dev/coder-cli/sdk2/client/organizations"
	"cdr.dev/coder-cli/sdk2/client/registries"
	"cdr.dev/coder-cli/sdk2/client/resource_pools"
	"cdr.dev/coder-cli/sdk2/client/users"
)

// Default coder HTTP API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new coder HTTP API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *CoderHTTPAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new coder HTTP API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *CoderHTTPAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new coder HTTP API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *CoderHTTPAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(CoderHTTPAPI)
	cli.Transport = transport
	cli.APIKeys = api_keys.New(transport, formats)
	cli.AuditLog = audit_log.New(transport, formats)
	cli.Config = config.New(transport, formats)
	cli.DevurLs = dev_u_r_ls.New(transport, formats)
	cli.Environments = environments.New(transport, formats)
	cli.Images = images.New(transport, formats)
	cli.Metrics = metrics.New(transport, formats)
	cli.Organizations = organizations.New(transport, formats)
	cli.Registries = registries.New(transport, formats)
	cli.ResourcePools = resource_pools.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// CoderHTTPAPI is a client for coder HTTP API
type CoderHTTPAPI struct {
	APIKeys api_keys.ClientService

	AuditLog audit_log.ClientService

	Config config.ClientService

	DevurLs dev_u_r_ls.ClientService

	Environments environments.ClientService

	Images images.ClientService

	Metrics metrics.ClientService

	Organizations organizations.ClientService

	Registries registries.ClientService

	ResourcePools resource_pools.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *CoderHTTPAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.APIKeys.SetTransport(transport)
	c.AuditLog.SetTransport(transport)
	c.Config.SetTransport(transport)
	c.DevurLs.SetTransport(transport)
	c.Environments.SetTransport(transport)
	c.Images.SetTransport(transport)
	c.Metrics.SetTransport(transport)
	c.Organizations.SetTransport(transport)
	c.Registries.SetTransport(transport)
	c.ResourcePools.SetTransport(transport)
	c.Users.SetTransport(transport)
}
