// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// AddOrgMemberReader is a Reader for the AddOrgMember structure.
type AddOrgMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddOrgMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddOrgMemberCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddOrgMemberCreated creates a AddOrgMemberCreated with default headers values
func NewAddOrgMemberCreated() *AddOrgMemberCreated {
	return &AddOrgMemberCreated{}
}

/* AddOrgMemberCreated describes a response with status code 201, with default header values.

Created
*/
type AddOrgMemberCreated struct {
	Payload *models.OrganizationUser
}

func (o *AddOrgMemberCreated) Error() string {
	return fmt.Sprintf("[POST /v0/orgs/{id}/members][%d] addOrgMemberCreated  %+v", 201, o.Payload)
}
func (o *AddOrgMemberCreated) GetPayload() *models.OrganizationUser {
	return o.Payload
}

func (o *AddOrgMemberCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
