// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// DeleteOrgReader is a Reader for the DeleteOrg structure.
type DeleteOrgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteOrgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOrgOK creates a DeleteOrgOK with default headers values
func NewDeleteOrgOK() *DeleteOrgOK {
	return &DeleteOrgOK{}
}

/* DeleteOrgOK describes a response with status code 200, with default header values.

OK
*/
type DeleteOrgOK struct {
	Payload *models.SuccessMsg
}

func (o *DeleteOrgOK) Error() string {
	return fmt.Sprintf("[DELETE /v0/orgs/{id}][%d] deleteOrgOK  %+v", 200, o.Payload)
}
func (o *DeleteOrgOK) GetPayload() *models.SuccessMsg {
	return o.Payload
}

func (o *DeleteOrgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMsg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
