// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetOrgMemberReader is a Reader for the GetOrgMember structure.
type GetOrgMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrgMemberOK creates a GetOrgMemberOK with default headers values
func NewGetOrgMemberOK() *GetOrgMemberOK {
	return &GetOrgMemberOK{}
}

/* GetOrgMemberOK describes a response with status code 200, with default header values.

OK
*/
type GetOrgMemberOK struct {
	Payload *models.OrganizationUser
}

func (o *GetOrgMemberOK) Error() string {
	return fmt.Sprintf("[GET /v0/orgs/{id}/members/{user_id}][%d] getOrgMemberOK  %+v", 200, o.Payload)
}
func (o *GetOrgMemberOK) GetPayload() *models.OrganizationUser {
	return o.Payload
}

func (o *GetOrgMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
