// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListOrgUsersParams creates a new ListOrgUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListOrgUsersParams() *ListOrgUsersParams {
	return &ListOrgUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListOrgUsersParamsWithTimeout creates a new ListOrgUsersParams object
// with the ability to set a timeout on a request.
func NewListOrgUsersParamsWithTimeout(timeout time.Duration) *ListOrgUsersParams {
	return &ListOrgUsersParams{
		timeout: timeout,
	}
}

// NewListOrgUsersParamsWithContext creates a new ListOrgUsersParams object
// with the ability to set a context for a request.
func NewListOrgUsersParamsWithContext(ctx context.Context) *ListOrgUsersParams {
	return &ListOrgUsersParams{
		Context: ctx,
	}
}

// NewListOrgUsersParamsWithHTTPClient creates a new ListOrgUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewListOrgUsersParamsWithHTTPClient(client *http.Client) *ListOrgUsersParams {
	return &ListOrgUsersParams{
		HTTPClient: client,
	}
}

/* ListOrgUsersParams contains all the parameters to send to the API endpoint
   for the list org users operation.

   Typically these are written to a http.Request.
*/
type ListOrgUsersParams struct {

	/* ID.

	   Org ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list org users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOrgUsersParams) WithDefaults() *ListOrgUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list org users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListOrgUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list org users params
func (o *ListOrgUsersParams) WithTimeout(timeout time.Duration) *ListOrgUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list org users params
func (o *ListOrgUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list org users params
func (o *ListOrgUsersParams) WithContext(ctx context.Context) *ListOrgUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list org users params
func (o *ListOrgUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list org users params
func (o *ListOrgUsersParams) WithHTTPClient(client *http.Client) *ListOrgUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list org users params
func (o *ListOrgUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list org users params
func (o *ListOrgUsersParams) WithID(id string) *ListOrgUsersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list org users params
func (o *ListOrgUsersParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListOrgUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
