// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// NewUpdateOrgMemberParams creates a new UpdateOrgMemberParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateOrgMemberParams() *UpdateOrgMemberParams {
	return &UpdateOrgMemberParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOrgMemberParamsWithTimeout creates a new UpdateOrgMemberParams object
// with the ability to set a timeout on a request.
func NewUpdateOrgMemberParamsWithTimeout(timeout time.Duration) *UpdateOrgMemberParams {
	return &UpdateOrgMemberParams{
		timeout: timeout,
	}
}

// NewUpdateOrgMemberParamsWithContext creates a new UpdateOrgMemberParams object
// with the ability to set a context for a request.
func NewUpdateOrgMemberParamsWithContext(ctx context.Context) *UpdateOrgMemberParams {
	return &UpdateOrgMemberParams{
		Context: ctx,
	}
}

// NewUpdateOrgMemberParamsWithHTTPClient creates a new UpdateOrgMemberParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateOrgMemberParamsWithHTTPClient(client *http.Client) *UpdateOrgMemberParams {
	return &UpdateOrgMemberParams{
		HTTPClient: client,
	}
}

/* UpdateOrgMemberParams contains all the parameters to send to the API endpoint
   for the update org member operation.

   Typically these are written to a http.Request.
*/
type UpdateOrgMemberParams struct {

	/* ID.

	   Org ID
	*/
	ID string

	/* Request.

	   Request body
	*/
	Request *models.UpdateOrganizationMemberRequest

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update org member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrgMemberParams) WithDefaults() *UpdateOrgMemberParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update org member params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateOrgMemberParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update org member params
func (o *UpdateOrgMemberParams) WithTimeout(timeout time.Duration) *UpdateOrgMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update org member params
func (o *UpdateOrgMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update org member params
func (o *UpdateOrgMemberParams) WithContext(ctx context.Context) *UpdateOrgMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update org member params
func (o *UpdateOrgMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update org member params
func (o *UpdateOrgMemberParams) WithHTTPClient(client *http.Client) *UpdateOrgMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update org member params
func (o *UpdateOrgMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update org member params
func (o *UpdateOrgMemberParams) WithID(id string) *UpdateOrgMemberParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update org member params
func (o *UpdateOrgMemberParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the update org member params
func (o *UpdateOrgMemberParams) WithRequest(request *models.UpdateOrganizationMemberRequest) *UpdateOrgMemberParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update org member params
func (o *UpdateOrgMemberParams) SetRequest(request *models.UpdateOrganizationMemberRequest) {
	o.Request = request
}

// WithUserID adds the userID to the update org member params
func (o *UpdateOrgMemberParams) WithUserID(userID string) *UpdateOrgMemberParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the update org member params
func (o *UpdateOrgMemberParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOrgMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
