// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// ListOrgRegistriesReader is a Reader for the ListOrgRegistries structure.
type ListOrgRegistriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOrgRegistriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOrgRegistriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListOrgRegistriesOK creates a ListOrgRegistriesOK with default headers values
func NewListOrgRegistriesOK() *ListOrgRegistriesOK {
	return &ListOrgRegistriesOK{}
}

/* ListOrgRegistriesOK describes a response with status code 200, with default header values.

OK
*/
type ListOrgRegistriesOK struct {
	Payload []*models.Registry
}

func (o *ListOrgRegistriesOK) Error() string {
	return fmt.Sprintf("[GET /v0/registries][%d] listOrgRegistriesOK  %+v", 200, o.Payload)
}
func (o *ListOrgRegistriesOK) GetPayload() []*models.Registry {
	return o.Payload
}

func (o *ListOrgRegistriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
