package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"

	"cdr.dev/coder-cli/internal/entclient"
	"github.com/spf13/pflag"

	"go.coder.com/cli"
	"go.coder.com/flog"
)

type configSSHCmd struct {
	filepath string
	remove   bool

	startToken, startMessage, endToken string
}

func (cmd *configSSHCmd) Spec() cli.CommandSpec {
	return cli.CommandSpec{
		Name:  "config-ssh",
		Usage: "",
		Desc:  "adds your Coder Enterprise environments to ~/.ssh/config",
	}
}

func (cmd *configSSHCmd) RegisterFlags(fl *pflag.FlagSet) {
	fl.BoolVar(&cmd.remove, "remove", false, "remove the auto-generated Coder Enterprise ssh config")
	defaultPath := filepath.Join(os.Getenv("HOME"), ".ssh", "config")
	fl.StringVar(&cmd.filepath, "config-path", defaultPath, "overide the default path of your ssh config file")

	cmd.startToken = "# ------------START-CODER-ENTERPRISE-----------"
	cmd.startMessage = `# The following has been auto-generated by "coder config-ssh"
# to make accessing your Coder Enterprise environments easier.
#
# To remove this blob, run:
#
#    coder config-ssh --remove
#
# You should not hand-edit this section, unless you are deleting it.`
	cmd.endToken = "# ------------END-CODER-ENTERPRISE------------"
}

func (cmd *configSSHCmd) Run(fl *pflag.FlagSet) {
	currentConfig, err := readStr(cmd.filepath)
	if err != nil {
		flog.Fatal("failed to read ssh config file %q: %v", cmd.filepath, err)
	}

	startIndex := strings.Index(currentConfig, cmd.startToken)
	endIndex := strings.Index(currentConfig, cmd.endToken)

	if cmd.remove {
		if startIndex == -1 || endIndex == -1 {
			flog.Fatal("the Coder Enterprise ssh configuration section could not be safely deleted or does not exist")
		}
		currentConfig = currentConfig[:startIndex-1] + currentConfig[endIndex+len(cmd.endToken)+1:]

		err = writeStr(cmd.filepath, currentConfig)
		if err != nil {
			flog.Fatal("failed to write to ssh config file %q: %v", cmd.filepath, err)
		}

		return
	}

	entClient := requireAuth()

	me, err := entClient.Me()
	if err != nil {
		flog.Fatal("failed to fetch username: %v", err)
	}

	envs := getEnvs(entClient)
	if len(envs) < 1 {
		flog.Fatal("no environments found")
	}
	newConfig := cmd.makeNewConfigs(me.Username, envs)

	// if we find the old config, remove those chars from the string
	if startIndex != -1 && endIndex != -1 {
		currentConfig = currentConfig[:startIndex-1] + currentConfig[endIndex+len(cmd.endToken)+1:]
	}

	err = writeStr(cmd.filepath, currentConfig+newConfig)
	if err != nil {
		flog.Fatal("failed to write new configurations to ssh config file %q: %v", cmd.filepath, err)
	}
	fmt.Printf("An auto-generated ssh config was written to %q\n", cmd.filepath)
	fmt.Println("You should now be able to ssh into your environment")
	fmt.Printf("For example, try running\n\n\t$ ssh coder:%s\n\n", envs[0].Name)
}

func (cmd *configSSHCmd) makeNewConfigs(userName string, envs []entclient.Environment) string {
	newConfig := fmt.Sprintf("\n%s\n%s\n\n", cmd.startToken, cmd.startMessage)
	for _, env := range envs {
		newConfig += makeConfig(userName, env.Name)
	}
	newConfig += fmt.Sprintf("\n%s\n", cmd.endToken)

	return newConfig
}

func makeConfig(userName, envName string) string {
	return fmt.Sprintf(
		`Host coder:%s
    HostName %s
    User %s-%s
    Port 2222
    KeepAlive=yes
    ConnectTimeout=0
`, envName, "MOCK-SSHPROXY-IP", userName, envName) // TODO: get real ssh proxy ip address
}

func writeStr(filename, data string) error {
	return ioutil.WriteFile(filename, []byte(data), 0777)
}

func readStr(filename string) (string, error) {
	contents, err := ioutil.ReadFile(filename)
	if err != nil {
		return "", err
	}
	return string(contents), nil
}
