// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetEnvironmentsReader is a Reader for the GetEnvironments structure.
type GetEnvironmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnvironmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnvironmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEnvironmentsOK creates a GetEnvironmentsOK with default headers values
func NewGetEnvironmentsOK() *GetEnvironmentsOK {
	return &GetEnvironmentsOK{}
}

/* GetEnvironmentsOK describes a response with status code 200, with default header values.

OK
*/
type GetEnvironmentsOK struct {
	Payload *GetEnvironmentsOKBody
}

func (o *GetEnvironmentsOK) Error() string {
	return fmt.Sprintf("[GET /v0/environments][%d] getEnvironmentsOK  %+v", 200, o.Payload)
}
func (o *GetEnvironmentsOK) GetPayload() *GetEnvironmentsOKBody {
	return o.Payload
}

func (o *GetEnvironmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetEnvironmentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetEnvironmentsOKBody get environments o k body
swagger:model GetEnvironmentsOKBody
*/
type GetEnvironmentsOKBody struct {
	models.PagedResponse

	// data
	Data []*models.Environment `json:"data"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetEnvironmentsOKBody) UnmarshalJSON(raw []byte) error {
	// GetEnvironmentsOKBodyAO0
	var getEnvironmentsOKBodyAO0 models.PagedResponse
	if err := swag.ReadJSON(raw, &getEnvironmentsOKBodyAO0); err != nil {
		return err
	}
	o.PagedResponse = getEnvironmentsOKBodyAO0

	// GetEnvironmentsOKBodyAO1
	var dataGetEnvironmentsOKBodyAO1 struct {
		Data []*models.Environment `json:"data"`
	}
	if err := swag.ReadJSON(raw, &dataGetEnvironmentsOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetEnvironmentsOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetEnvironmentsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getEnvironmentsOKBodyAO0, err := swag.WriteJSON(o.PagedResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getEnvironmentsOKBodyAO0)
	var dataGetEnvironmentsOKBodyAO1 struct {
		Data []*models.Environment `json:"data"`
	}

	dataGetEnvironmentsOKBodyAO1.Data = o.Data

	jsonDataGetEnvironmentsOKBodyAO1, errGetEnvironmentsOKBodyAO1 := swag.WriteJSON(dataGetEnvironmentsOKBodyAO1)
	if errGetEnvironmentsOKBodyAO1 != nil {
		return nil, errGetEnvironmentsOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetEnvironmentsOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get environments o k body
func (o *GetEnvironmentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.PagedResponse
	if err := o.PagedResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetEnvironmentsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getEnvironmentsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get environments o k body based on the context it is used
func (o *GetEnvironmentsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.PagedResponse
	if err := o.PagedResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetEnvironmentsOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getEnvironmentsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetEnvironmentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetEnvironmentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetEnvironmentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
