// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetEnvironmentLimitsReader is a Reader for the GetEnvironmentLimits structure.
type GetEnvironmentLimitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnvironmentLimitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnvironmentLimitsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEnvironmentLimitsOK creates a GetEnvironmentLimitsOK with default headers values
func NewGetEnvironmentLimitsOK() *GetEnvironmentLimitsOK {
	return &GetEnvironmentLimitsOK{}
}

/* GetEnvironmentLimitsOK describes a response with status code 200, with default header values.

OK
*/
type GetEnvironmentLimitsOK struct {
	Payload *models.EnvironmentLimits
}

func (o *GetEnvironmentLimitsOK) Error() string {
	return fmt.Sprintf("[GET /v0/environments/limits][%d] getEnvironmentLimitsOK  %+v", 200, o.Payload)
}
func (o *GetEnvironmentLimitsOK) GetPayload() *models.EnvironmentLimits {
	return o.Payload
}

func (o *GetEnvironmentLimitsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnvironmentLimits)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
