// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopEnvironmentsParams creates a new StopEnvironmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopEnvironmentsParams() *StopEnvironmentsParams {
	return &StopEnvironmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopEnvironmentsParamsWithTimeout creates a new StopEnvironmentsParams object
// with the ability to set a timeout on a request.
func NewStopEnvironmentsParamsWithTimeout(timeout time.Duration) *StopEnvironmentsParams {
	return &StopEnvironmentsParams{
		timeout: timeout,
	}
}

// NewStopEnvironmentsParamsWithContext creates a new StopEnvironmentsParams object
// with the ability to set a context for a request.
func NewStopEnvironmentsParamsWithContext(ctx context.Context) *StopEnvironmentsParams {
	return &StopEnvironmentsParams{
		Context: ctx,
	}
}

// NewStopEnvironmentsParamsWithHTTPClient creates a new StopEnvironmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopEnvironmentsParamsWithHTTPClient(client *http.Client) *StopEnvironmentsParams {
	return &StopEnvironmentsParams{
		HTTPClient: client,
	}
}

/* StopEnvironmentsParams contains all the parameters to send to the API endpoint
   for the stop environments operation.

   Typically these are written to a http.Request.
*/
type StopEnvironmentsParams struct {

	/* ID.

	   Environment ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopEnvironmentsParams) WithDefaults() *StopEnvironmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop environments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopEnvironmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop environments params
func (o *StopEnvironmentsParams) WithTimeout(timeout time.Duration) *StopEnvironmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop environments params
func (o *StopEnvironmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop environments params
func (o *StopEnvironmentsParams) WithContext(ctx context.Context) *StopEnvironmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop environments params
func (o *StopEnvironmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop environments params
func (o *StopEnvironmentsParams) WithHTTPClient(client *http.Client) *StopEnvironmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop environments params
func (o *StopEnvironmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the stop environments params
func (o *StopEnvironmentsParams) WithID(id string) *StopEnvironmentsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the stop environments params
func (o *StopEnvironmentsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StopEnvironmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
