// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// StopEnvironmentsReader is a Reader for the StopEnvironments structure.
type StopEnvironmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopEnvironmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopEnvironmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopEnvironmentsOK creates a StopEnvironmentsOK with default headers values
func NewStopEnvironmentsOK() *StopEnvironmentsOK {
	return &StopEnvironmentsOK{}
}

/* StopEnvironmentsOK describes a response with status code 200, with default header values.

OK
*/
type StopEnvironmentsOK struct {
	Payload *models.SuccessMsg
}

func (o *StopEnvironmentsOK) Error() string {
	return fmt.Sprintf("[PUT /v0/environments/{id}/stop][%d] stopEnvironmentsOK  %+v", 200, o.Payload)
}
func (o *StopEnvironmentsOK) GetPayload() *models.SuccessMsg {
	return o.Payload
}

func (o *StopEnvironmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMsg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
