// Code generated by go-swagger; DO NOT EDIT.

package audit_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetAuditReader is a Reader for the GetAudit structure.
type GetAuditReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuditReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuditOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAuditOK creates a GetAuditOK with default headers values
func NewGetAuditOK() *GetAuditOK {
	return &GetAuditOK{}
}

/* GetAuditOK describes a response with status code 200, with default header values.

OK
*/
type GetAuditOK struct {
	Payload []*models.AuditLog
}

func (o *GetAuditOK) Error() string {
	return fmt.Sprintf("[GET /v0/audit][%d] getAuditOK  %+v", 200, o.Payload)
}
func (o *GetAuditOK) GetPayload() []*models.AuditLog {
	return o.Payload
}

func (o *GetAuditOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
