// Code generated by go-swagger; DO NOT EDIT.

package audit_log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"cdr.dev/coder-cli/sdk2/models"
)

// GetAuditCountReader is a Reader for the GetAuditCount structure.
type GetAuditCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuditCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuditCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAuditCountOK creates a GetAuditCountOK with default headers values
func NewGetAuditCountOK() *GetAuditCountOK {
	return &GetAuditCountOK{}
}

/* GetAuditCountOK describes a response with status code 200, with default header values.

OK
*/
type GetAuditCountOK struct {
	Payload *models.AuditCountResponse
}

func (o *GetAuditCountOK) Error() string {
	return fmt.Sprintf("[GET /v0/audit/count][%d] getAuditCountOK  %+v", 200, o.Payload)
}
func (o *GetAuditCountOK) GetPayload() *models.AuditCountResponse {
	return o.Payload
}

func (o *GetAuditCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuditCountResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
