// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddOrganizationMemberRequest add organization member request
//
// swagger:model AddOrganizationMemberRequest
type AddOrganizationMemberRequest struct {

	// roles
	Roles []string `json:"roles"`

	// user id
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this add organization member request
func (m *AddOrganizationMemberRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add organization member request based on context it is used
func (m *AddOrganizationMemberRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddOrganizationMemberRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddOrganizationMemberRequest) UnmarshalBinary(b []byte) error {
	var res AddOrganizationMemberRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
