// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIKey API key
//
// swagger:model APIKey
type APIKey struct {

	// application
	Application bool `json:"application,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last used
	LastUsed string `json:"last_used,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this API key
func (m *APIKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API key based on context it is used
func (m *APIKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKey) UnmarshalBinary(b []byte) error {
	var res APIKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
