// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigEnvironments config environments
//
// swagger:model ConfigEnvironments
type ConfigEnvironments struct {

	// EnableContainerVMs allows users to create environments as
	// container-based virtual machines with sysbox.
	EnableContainerVms bool `json:"enable_container_vms,omitempty"`

	// GPUVendor can be set to "nvidia" or "amd" to allow environments to
	// be created with GPUs. If set to an empty string, environments can
	// not be created with GPUs.
	GpuVendor string `json:"gpu_vendor,omitempty"`
}

// Validate validates this config environments
func (m *ConfigEnvironments) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config environments based on context it is used
func (m *ConfigEnvironments) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigEnvironments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigEnvironments) UnmarshalBinary(b []byte) error {
	var res ConfigEnvironments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
