// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateDevURLRequest create dev URL request
//
// swagger:model CreateDevURLRequest
type CreateDevURLRequest struct {

	// access
	Access string `json:"access,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// scheme
	Scheme string `json:"scheme,omitempty"`
}

// Validate validates this create dev URL request
func (m *CreateDevURLRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create dev URL request based on context it is used
func (m *CreateDevURLRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateDevURLRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateDevURLRequest) UnmarshalBinary(b []byte) error {
	var res CreateDevURLRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
