// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Cursor cursor
//
// swagger:model Cursor
type Cursor struct {

	// After is the last value in the page.
	After string `json:"after,omitempty"`

	// Before is the first value in the page.
	Before string `json:"before,omitempty"`
}

// Validate validates this cursor
func (m *Cursor) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cursor based on context it is used
func (m *Cursor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Cursor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cursor) UnmarshalBinary(b []byte) error {
	var res Cursor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
