// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GenerateApplicationAPIKeyResponse generate application API key response
//
// swagger:model GenerateApplicationAPIKeyResponse
type GenerateApplicationAPIKeyResponse struct {

	// key
	Key string `json:"key,omitempty"`
}

// Validate validates this generate application API key response
func (m *GenerateApplicationAPIKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this generate application API key response based on context it is used
func (m *GenerateApplicationAPIKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GenerateApplicationAPIKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GenerateApplicationAPIKeyResponse) UnmarshalBinary(b []byte) error {
	var res GenerateApplicationAPIKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
