// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImportImageTagRequest import image tag request
//
// swagger:model ImportImageTagRequest
type ImportImageTagRequest struct {

	// default
	Default bool `json:"default,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this import image tag request
func (m *ImportImageTagRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this import image tag request based on context it is used
func (m *ImportImageTagRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImportImageTagRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImportImageTagRequest) UnmarshalBinary(b []byte) error {
	var res ImportImageTagRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
