// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationUser organization user
//
// swagger:model OrganizationUser
type OrganizationUser struct {

	// avatar hash
	AvatarHash string `json:"avatar_hash,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// dotfiles git uri
	DotfilesGitURI string `json:"dotfiles_git_uri,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// has active environments
	HasActiveEnvironments bool `json:"has_active_environments,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// joined at
	JoinedAt string `json:"joined_at,omitempty"`

	// key regenerated at
	KeyRegeneratedAt string `json:"key_regenerated_at,omitempty"`

	// LoginType is only returned to admin users.
	LoginType string `json:"login_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization roles
	OrganizationRoles []string `json:"organization_roles"`

	// Relatime is only returned to admin users.
	Relatime string `json:"relatime,omitempty"`

	// roles
	Roles []string `json:"roles"`

	// roles updated at
	RolesUpdatedAt string `json:"roles_updated_at,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// TemporaryPassword is only returned to admin users.
	TemporaryPassword bool `json:"temporary_password,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this organization user
func (m *OrganizationUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization user based on context it is used
func (m *OrganizationUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationUser) UnmarshalBinary(b []byte) error {
	var res OrganizationUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
