// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PagedResponse paged response
//
// swagger:model PagedResponse
type PagedResponse struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// pager
	Pager *Pager `json:"pager,omitempty"`
}

// Validate validates this paged response
func (m *PagedResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePager(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PagedResponse) validatePager(formats strfmt.Registry) error {
	if swag.IsZero(m.Pager) { // not required
		return nil
	}

	if m.Pager != nil {
		if err := m.Pager.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pager")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this paged response based on the context it is used
func (m *PagedResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePager(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PagedResponse) contextValidatePager(ctx context.Context, formats strfmt.Registry) error {

	if m.Pager != nil {
		if err := m.Pager.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pager")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PagedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PagedResponse) UnmarshalBinary(b []byte) error {
	var res PagedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
