// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RebuildMessage rebuild message
//
// swagger:model RebuildMessage
type RebuildMessage struct {

	// required
	Required bool `json:"required,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this rebuild message
func (m *RebuildMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rebuild message based on context it is used
func (m *RebuildMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RebuildMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RebuildMessage) UnmarshalBinary(b []byte) error {
	var res RebuildMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
