// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Registry registry
//
// swagger:model Registry
type Registry struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// friendly name
	FriendlyName string `json:"friendly_name,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// organization id
	OrganizationID string `json:"organization_id,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this registry
func (m *Registry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this registry based on context it is used
func (m *Registry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Registry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Registry) UnmarshalBinary(b []byte) error {
	var res Registry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
