// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SuccessMsg success msg
//
// swagger:model SuccessMsg
type SuccessMsg struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this success msg
func (m *SuccessMsg) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this success msg based on context it is used
func (m *SuccessMsg) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SuccessMsg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SuccessMsg) UnmarshalBinary(b []byte) error {
	var res SuccessMsg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
