// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateOrganizationMemberRequest update organization member request
//
// swagger:model UpdateOrganizationMemberRequest
type UpdateOrganizationMemberRequest struct {

	// roles
	Roles []string `json:"roles"`
}

// Validate validates this update organization member request
func (m *UpdateOrganizationMemberRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update organization member request based on context it is used
func (m *UpdateOrganizationMemberRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateOrganizationMemberRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateOrganizationMemberRequest) UnmarshalBinary(b []byte) error {
	var res UpdateOrganizationMemberRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
