// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRegistryRequest update registry request
//
// swagger:model UpdateRegistryRequest
type UpdateRegistryRequest struct {

	// friendly name
	FriendlyName string `json:"friendly_name,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// registry
	Registry string `json:"registry,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this update registry request
func (m *UpdateRegistryRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update registry request based on context it is used
func (m *UpdateRegistryRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRegistryRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRegistryRequest) UnmarshalBinary(b []byte) error {
	var res UpdateRegistryRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
