// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateOrganizationSpec update organization spec
//
// swagger:model UpdateOrganizationSpec
type UpdateOrganizationSpec struct {

	// auto off threshold
	AutoOffThreshold int64 `json:"auto_off_threshold,omitempty"`

	// cpu provisioning rate
	CPUProvisioningRate float64 `json:"cpu_provisioning_rate,omitempty"`

	// default
	Default bool `json:"default,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// memory provisioning rate
	MemoryProvisioningRate float64 `json:"memory_provisioning_rate,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update organization spec
func (m *UpdateOrganizationSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update organization spec based on context it is used
func (m *UpdateOrganizationSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateOrganizationSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateOrganizationSpec) UnmarshalBinary(b []byte) error {
	var res UpdateOrganizationSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
