// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateUserRequest update user request
//
// swagger:model UpdateUserRequest
type UpdateUserRequest struct {

	// dotfiles git uri
	DotfilesGitURI string `json:"dotfiles_git_uri,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// login type
	LoginType string `json:"login_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// old password
	OldPassword string `json:"old_password,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// revoked
	Revoked bool `json:"revoked,omitempty"`

	// roles
	Roles []string `json:"roles"`

	// temporary password
	TemporaryPassword bool `json:"temporary_password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this update user request
func (m *UpdateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update user request based on context it is used
func (m *UpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res UpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
