// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UsageMetricResources usage metric resources
//
// swagger:model UsageMetricResources
type UsageMetricResources struct {

	// envs
	Envs []int64 `json:"envs"`

	// orgs
	Orgs []int64 `json:"orgs"`

	// users
	Users []int64 `json:"users"`
}

// Validate validates this usage metric resources
func (m *UsageMetricResources) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this usage metric resources based on context it is used
func (m *UsageMetricResources) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UsageMetricResources) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UsageMetricResources) UnmarshalBinary(b []byte) error {
	var res UsageMetricResources
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
