// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// User user
//
// swagger:model User
type User struct {

	// avatar hash
	AvatarHash string `json:"avatar_hash,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// dotfiles git uri
	DotfilesGitURI string `json:"dotfiles_git_uri,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// key regenerated at
	KeyRegeneratedAt string `json:"key_regenerated_at,omitempty"`

	// LoginType is only returned to admin users.
	LoginType string `json:"login_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Relatime is only returned to admin users.
	Relatime string `json:"relatime,omitempty"`

	// roles
	Roles []string `json:"roles"`

	// status
	Status string `json:"status,omitempty"`

	// TemporaryPassword is only returned to admin users.
	TemporaryPassword bool `json:"temporary_password,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user based on context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
