// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserAgent user agent
//
// swagger:model UserAgent
type UserAgent struct {

	// browser
	Browser string `json:"browser,omitempty"`

	// device
	Device string `json:"device,omitempty"`

	// ip address
	IPAddress string `json:"ip_address,omitempty"`

	// os
	Os string `json:"os,omitempty"`
}

// Validate validates this user agent
func (m *UserAgent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user agent based on context it is used
func (m *UserAgent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserAgent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserAgent) UnmarshalBinary(b []byte) error {
	var res UserAgent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
